version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    # pgadmin service configuration...

  ansible:
      image: project1/ansible
    # Add any other configurations specific to your Ansible setup here     



volumes:
  pgdata:

