version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Rockerz88
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: liban.omer4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Rockerz88@@
    ports:
      - 5050:80
    # pgadmin service configuration...

volumes:
  pgdata:
