name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Backend Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.backend
        tags: 147188/project1_backend:latest
        push: false

        # name: Run Trivy vulnerability scanner on Backend
        #uses: aquasecurity/trivy-action@master
        #with:
        #image-ref: '147188/project1_backend:latest'
        #exit-code: '1'
        #severity: 'CRITICAL,HIGH'
        #ignore-unfixed: 'false'

    - name: Push Backend Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.backend
        tags: 147188/project1_backend:latest
        push: true

    - name: Build Frontend Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.frontend
        tags: 147188/project1_frontend:latest
        push: false

    - name: Run Trivy vulnerability scanner on Frontend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '147188/project1_frontend:latest'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: 'false'

    - name: Push Frontend Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.frontend
        tags: 147188/project1_frontend:latest
        push: true

