name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.backend
        tags: 147188/project1_backend:latest
        push: true

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.frontend
        tags: 147188/project1_frontend:latest
        push: true

